# Generated by Django 5.0.3 on 2026-04-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_blood_group_studentprofile_category_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE students_studentprofile "
                        "ADD COLUMN IF NOT EXISTS roll_number varchar(20) NULL;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE students_studentprofile "
                        "DROP COLUMN IF EXISTS roll_number;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='studentprofile',
                    name='roll_number',
                    field=models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "DO $$ BEGIN "
                        "IF NOT EXISTS ("
                        "SELECT 1 FROM pg_constraint WHERE conname = 'unique_roll_per_class_section'"
                        ") THEN "
                        "ALTER TABLE students_studentprofile "
                        "ADD CONSTRAINT unique_roll_per_class_section "
                        "UNIQUE (class_section_id, roll_number); "
                        "END IF; "
                        "END $$;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE students_studentprofile "
                        "DROP CONSTRAINT IF EXISTS unique_roll_per_class_section;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name='studentprofile',
                    constraint=models.UniqueConstraint(
                        fields=('class_section', 'roll_number'),
                        name='unique_roll_per_class_section',
                    ),
                ),
            ],
        ),
    ]
