# Generated by Django 6.0.3 on 2026-04-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_studentprofile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='parent_contact_number',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='parent_guardian_name',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bus_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
