# Generated by Django 5.0.3 on 2026-03-31 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacherprofile_dob_teacherprofile_experience_years_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='teachers.teacherprofile')),
            ],
        ),
    ]
