# Generated by Django 5.0.3 on 2026-04-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_documents'),
        ('teachers', '0003_teacherprofiledocument'),
    ]

    operations = [
    ]
