# Generated by Django 5.0.3 on 2026-04-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_merge_20260401_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherProfileDocument',
        ),
    ]
