# Generated by Django 6.0.3 on 2026-04-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classsection_school_mainclass_school_and_more'),
        ('subjects', '0001_initial'),
        ('teachers', '0005_delete_teacherprofiledocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectassignment',
            name='school',
        ),
        migrations.RemoveField(
            model_name='subjectnote',
            name='school',
        ),
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('teacher', 'class_ref', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('class_ref', 'name')},
        ),
        migrations.RemoveField(
            model_name='teacherassignment',
            name='school',
        ),
    ]
