# Generated by Django 5.0.3 on 2026-03-31 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_exam_description_exam_end_date_exam_exam_type_and_more'),
        ('classes', '0002_classsection_room_number_mainclass_code_and_more'),
        ('teachers', '0002_teacherprofile_dob_teacherprofile_experience_years_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('class_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academics_subjects', to='classes.mainclass')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTeacherMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='classes.classsection')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_mappings', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_subjects', to='teachers.teacherprofile')),
            ],
            options={
                'unique_together': {('subject', 'class_section')},
            },
        ),
    ]
